name: crisis_flow
description: CrisisFlow — Smart Resource Allocation for Social Impact. Google Solution Challenge 2026.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  go_router: ^14.0.0
  percent_indicator: ^4.2.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  image_picker: ^1.1.2
  http: ^1.2.2
  file_picker: ^8.1.2
  flutter_dotenv: ^5.2.1
  permission_handler: ^11.3.1
  record: ^5.1.2       
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  latlong2: ^0.9.1
  csv: ^6.0.0
  google_mlkit_text_recognition: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
